#[derive(Debug, Clone, Copy)]
pub struct GlyphInfo {
    pub uv: [f32; 4], // [char_id, 0.0, 1.0, 1.0]
    pub advance: f32,
    pub bearing_x: f32,
    pub bearing_y: f32,
    pub width: f32,
    pub height: f32,
}

pub fn lookup(c: char) -> Option<GlyphInfo> {
    // Character index mapping in " ><_^ -ox0123456789ABCDEF:."
    match c {
        ' ' => Some(GlyphInfo {
            uv: [0.0, 0.0, 1.0, 1.0],
            advance: 0.4,
            bearing_x: 0.0,
            bearing_y: 0.0,
            width: 0.0,
            height: 0.0,
        }),
        '>' => Some(GlyphInfo {
            uv: [1.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '<' => Some(GlyphInfo {
            uv: [2.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '_' => Some(GlyphInfo {
            uv: [3.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '^' => Some(GlyphInfo {
            uv: [4.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '-' => Some(GlyphInfo {
            uv: [6.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'o' | 'O' => Some(GlyphInfo {
            uv: [7.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'x' | 'X' => Some(GlyphInfo {
            uv: [8.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '0' => Some(GlyphInfo {
            uv: [9.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '1' => Some(GlyphInfo {
            uv: [10.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '2' => Some(GlyphInfo {
            uv: [11.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '3' => Some(GlyphInfo {
            uv: [12.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '4' => Some(GlyphInfo {
            uv: [13.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '5' => Some(GlyphInfo {
            uv: [14.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '6' => Some(GlyphInfo {
            uv: [15.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '7' => Some(GlyphInfo {
            uv: [16.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '8' => Some(GlyphInfo {
            uv: [17.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '9' => Some(GlyphInfo {
            uv: [18.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'a' | 'A' => Some(GlyphInfo {
            uv: [19.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'b' | 'B' => Some(GlyphInfo {
            uv: [20.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'c' | 'C' => Some(GlyphInfo {
            uv: [21.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'd' | 'D' => Some(GlyphInfo {
            uv: [22.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'e' | 'E' => Some(GlyphInfo {
            uv: [23.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        'f' | 'F' => Some(GlyphInfo {
            uv: [24.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        ':' => Some(GlyphInfo {
            uv: [25.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        '.' => Some(GlyphInfo {
            uv: [26.0, 0.0, 1.0, 1.0],
            advance: 0.6,
            bearing_x: 0.0,
            bearing_y: 0.8,
            width: 0.6,
            height: 0.8,
        }),
        _ => None,
    }
}
